name: build fuguquest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Henry1887/fuguquest

      - uses: dtolnay/rust-toolchain@stable

      - name: build
        run: |
          cd rust
          cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: fuguquest-windows
          path: rust\target\release\fuguquest.exe
